version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432:5432"
###< doctrine/doctrine-bundle ###

  adminer:
    image: adminer
    environment:
      ADMINER_DEFAULT_SERVER: database
    ports:
      - "8080:8080"
